---
- hosts: websphere_servers
  become: yes        
  become_user: root 
  tasks:
    - name: ensure selinux is set to permissive
      selinux:
        policy: targeted
        state: permissive
      register: selinux_status
    - name: reboot server if status of selinux changed.
      reboot:
        msg: "Reboot initiated from Ansible"
        connect_timeout: 30
        reboot_timeout: 120
        test_command: whoami
      when: selinux_status.changed == true
