---
- hosts: websphere_servers
  become: yes        
  become_user: root 
  tasks:
    - name: ensure selinux is set to permissive
      selinux:
        policy: targeted
        state: permissive
      notify: reboot

    - name: set number of open files in limits.conf
      pam_limits:
        domain: root
        limit_type: '-'
        limit_item: nofile
        value: "65535"
      notify: reboot
      
  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated from Ansible"
        connect_timeout: 30
        reboot_timeout: 120
        test_command: whoami
