---
- hosts: websphere_servers
  become: yes        
  become_user: root 
  tasks:
    - name: ensure selinux is set to permissive
      selinux:
        policy: targeted
        state: permissive
      notify: reboot
  handlers:
    - name: reboot
      reboot:
        msg: "Reboot initiated from Ansible"
        connect_timeout: 30
        reboot_timeout: 120
        test_command: whoami
