---
- hosts: websphere_servers
  become: yes        
  become_user: root 
  tasks:
    - name: ensure selinux is set to permissive
      selinux:
        policy: targeted
        state: permissive
      register: selinux_status
    - debug:
        msg: "SELinux changed. Please reboot"
      when: selinux_status.changed == true
